// The corner in headless Helium over a fresh profile: seed the fixtures,
// read the indicator after the warm and past its whisper, type and wait
// for "saved", click it away, press ⌃⌘, at the first entry; prints what
// the span and the pill read at each step, the masthead over a verse
// page, then the pill under
// `?corner=pill`, then the console.
// `node tools/helium-corner.mjs [profileDir] [screenshot.png]`.
import { chromium } from "playwright-core";
import { resolve } from "node:path";
const H = "/Applications/Helium.app/Contents/MacOS/Helium";
const PAGE = "file://" + resolve("dist/index.html");
const PROFILE = process.argv[2] || resolve("tools/out/helium-corner-profile");
const logs = [];
const ctx = await chromium.launchPersistentContext(PROFILE, { executablePath: H, headless: true, viewport: { width: 1000, height: 600 } });
const page = await ctx.newPage();
page.on("console", (m) => logs.push(m.type() + ": " + m.text()));
page.on("pageerror", (e) => logs.push("pageerror: " + e.message));
await page.goto(PAGE + "?store=seed#page/Horace");
await page.waitForFunction(() => document.documentElement.dataset.probe?.includes("all;"), null, { timeout: 15000 });
const corner = () => page.evaluate(() => { const s = document.querySelector(".saved"); return { text: s?.textContent, show: s?.classList.contains("show"), opacity: getComputedStyle(s).opacity, pill: document.querySelector(".backup-paused")?.hidden }; });
console.log("after warm:", JSON.stringify(await corner()));
console.log("masthead over Horace:", JSON.stringify(await page.evaluate(() => { const h = document.querySelector(".site-head"); const r = h.getBoundingClientRect(); return { crumb: document.querySelector(".datelabel")?.textContent.replace(/\s+/g, " ").trim(), title: document.querySelector(".page-title")?.textContent, titleHidden: document.querySelector(".page-title")?.hidden, lines: !document.querySelector(".page-lines")?.hidden, today: !document.querySelector(".toolbtn[title='Go to today']")?.hidden, backups: document.querySelector(".toolbtn[title='Automatic folder backups']")?.textContent, height: r.height, sticky: getComputedStyle(h).position }; })));
if (process.argv[3]) await page.screenshot({ path: process.argv[3].replace(/\.png$/, "-masthead.png"), clip: { x: 0, y: 0, width: 1000, height: 130 } });
const panel = () => page.evaluate(() => { const p = document.querySelector(".pages"); return p ? { rows: [...p.querySelectorAll("a")].map((a) => a.textContent), create: p.querySelector(".panel-new")?.textContent, empty: p.querySelector(".panel-empty")?.textContent } : null; });
await page.click(".opener[title='Open the pages list']");
console.log("pages panel:", JSON.stringify(await panel()));
if (process.argv[3]) await page.screenshot({ path: process.argv[3].replace(/\.png$/, "-panel.png"), clip: { x: 0, y: 0, width: 600, height: 260 } });
await page.click(".opener[title='List the authors on the bookshelf']");
console.log("books panel, displacing it:", JSON.stringify(await panel()));
await page.click(".opener[title='List the authors on the bookshelf']");
console.log("its own opener again:", JSON.stringify(await panel()));
await page.click(".opener[title='Open the pages list']");
await page.keyboard.press("Escape");
console.log("after Escape:", JSON.stringify(await panel()));
await page.click(".opener[title='Open the pages list']");
await page.mouse.click(500, 400);
console.log("after a click outside:", JSON.stringify(await panel()));
await page.click(".opener[title='Open the pages list']");
await page.click(".pages a[title='Williams']");
await page.waitForFunction(() => document.documentElement.dataset.entry === "page/Williams", null, { timeout: 5000 });
console.log("after a row click:", JSON.stringify({ entry: await page.evaluate(() => document.documentElement.dataset.entry), panel: await panel() }));
await page.waitForTimeout(3200);
console.log("3.2 s later:", JSON.stringify(await corner()));
await page.click("#editor .ProseMirror");
await page.keyboard.press("End");
await page.keyboard.type(" corner");
await page.waitForFunction(() => document.querySelector(".saved.show")?.textContent === "saved", null, { timeout: 5000 });
console.log("after typing:", JSON.stringify(await corner()));
if (process.argv[3]) await page.screenshot({ path: process.argv[3], clip: { x: 0, y: 500, width: 500, height: 100 } });
await page.click(".saved.show");
console.log("after the click:", JSON.stringify(await corner()));
await page.keyboard.press("Control+Meta+,");
await page.waitForTimeout(100);
console.log("after ⌃⌘, on the first entry:", JSON.stringify(await corner()));
await page.goto(PAGE + "#page/Links");
await page.waitForFunction(() => document.documentElement.dataset.entry === "page/Links", null, { timeout: 15000 });
await page.click("#editor a[href='#page/Links']");
await page.waitForTimeout(200);
console.log("a link to itself:", JSON.stringify({ entry: await page.evaluate(() => document.documentElement.dataset.entry), ...(await corner()) }));
await page.click("#editor a[href='https://example.org/']");
await page.waitForTimeout(200);
console.log("a plain click on an external link:", JSON.stringify({ entry: await page.evaluate(() => document.documentElement.dataset.entry), url: page.url().split("#")[1] }));
const popup = ctx.waitForEvent("page", { timeout: 5000 }).then((p) => p.url(), () => "(no new tab)");
await page.click("#editor a[href='#page/Horace']", { modifiers: ["Meta"] });
console.log("⌘-click on an internal link:", JSON.stringify({ newTab: (await popup).split("#")[1], stayed: await page.evaluate(() => document.documentElement.dataset.entry) }));
await page.click("#editor a[href='#page/Horace']");
await page.waitForFunction(() => document.documentElement.dataset.entry === "page/Horace", null, { timeout: 5000 });
console.log("a plain click on an internal link:", JSON.stringify({ entry: await page.evaluate(() => document.documentElement.dataset.entry) }));
/* code: a fence with a language typed, its tokens coloured, the label in the corner, the copy button on hover */
await page.goto(PAGE + "#page/Coded");
await page.waitForFunction(() => document.documentElement.dataset.entry === "page/Coded", null, { timeout: 15000 });
await page.click("#editor .ProseMirror");
await page.keyboard.type("```js");
await page.keyboard.press("Enter");
await page.keyboard.type("const n = 42 // answer");
await page.waitForTimeout(150);
console.log("a js block typed:", JSON.stringify(await page.evaluate(() => { const pre = document.querySelector("#editor pre"); return { lang: pre.dataset.lang, label: getComputedStyle(pre, "::after").content, tokens: [...pre.querySelectorAll("[class^=tok-]")].map((t) => t.className + ":" + t.textContent) }; })));
await page.hover("#editor pre");
await page.waitForTimeout(150);
console.log("hovered:", JSON.stringify(await page.evaluate(() => { const b = document.querySelector(".copybtn"); const pre = document.querySelector("#editor pre").getBoundingClientRect(); const r = b.getBoundingClientRect(); return { show: b.classList.contains("show"), title: b.title, insideBlock: r.top >= pre.top && r.right <= pre.right + 1, labelHidden: getComputedStyle(document.querySelector("#editor pre"), "::after").opacity }; })));
await page.click(".copybtn");
await page.waitForTimeout(300);
console.log("clicked:", JSON.stringify(await page.evaluate(() => document.querySelector(".copybtn").textContent)));
/* a pasted picture: a PNG drawn on a canvas, pasted as a file, filed beside the entry and placed */
await page.goto(PAGE + "#page/Pictured");
await page.waitForFunction(() => document.documentElement.dataset.entry === "page/Pictured", null, { timeout: 15000 });
await page.click("#editor .ProseMirror");
await page.keyboard.type("A picture: ");
await page.evaluate(async () => { const c = document.createElement("canvas"); c.width = 1600; c.height = 800; const x = c.getContext("2d"); x.fillStyle = "#c33"; x.fillRect(0, 0, 1600, 800); const blob = await new Promise((r) => c.toBlob(r, "image/png")); const dt = new DataTransfer(); dt.items.add(new File([blob], "shot.png", { type: "image/png" })); document.querySelector("#editor .ProseMirror").dispatchEvent(new ClipboardEvent("paste", { clipboardData: dt, bubbles: true, cancelable: true })); });
await page.waitForFunction(() => document.querySelector("#editor img"), null, { timeout: 8000 });
await page.waitForFunction(() => document.querySelector(".saved.show")?.textContent === "saved", null, { timeout: 5000 }).catch(() => {});
console.log("a picture pasted:", JSON.stringify(await page.evaluate(() => { const img = document.querySelector("#editor img"); return { md: document.getElementById("out").textContent, src: img.getAttribute("src")?.slice(0, 5), width: img.naturalWidth, height: img.naturalHeight, last: document.querySelector("#editor .ProseMirror").lastElementChild?.tagName }; })));
/* shortcuts: ⌃⌘S with an empty table opens the editor; a table saved; a code typed and Enter inserts at the caret */
await page.goto(PAGE + "#page/Expanded");
await page.waitForFunction(() => document.documentElement.dataset.entry === "page/Expanded", null, { timeout: 15000 });
await page.click("#editor .ProseMirror");
await page.keyboard.press("Control+Meta+s");
await page.waitForTimeout(150);
const scard = () => page.evaluate(() => { const c = document.querySelector(".shortcuts"); return c ? { rows: [...c.querySelectorAll("li")].map((li) => li.textContent.trim()), editor: !!c.querySelector(".shortcut-edit"), focused: document.activeElement?.className.split(" ")[0] } : null; });
console.log("⌃⌘S, no table yet:", JSON.stringify(await scard()));
await page.fill(".shortcuts .shortcut-edit", "sig: Sean Miller\nmd: markdown");
await page.click(".shortcuts .editbox .toolbtn");
await page.waitForTimeout(150);
console.log("saved:", JSON.stringify({ ...(await scard()), corner: await page.evaluate(() => document.querySelector(".saved.show")?.textContent) }));
await page.click(".shortcuts .search-input");
await page.keyboard.type("m");
await page.waitForTimeout(100);
console.log("m typed:", JSON.stringify((await scard()).rows));
await page.keyboard.press("Enter");
await page.waitForTimeout(200);
console.log("Enter:", JSON.stringify({ card: await scard(), text: await page.evaluate(() => document.querySelector("#editor .ProseMirror").textContent.slice(0, 30)) }));
/* bookmarks: ⌃⌘B on a day, A adds it, 1 jumps to it from elsewhere, a key given and typed, × deletes */
await page.goto(PAGE + "#2026-09-06");
await page.waitForFunction(() => document.documentElement.dataset.entry === "2026-09-06", null, { timeout: 15000 });
await page.keyboard.press("Control+Meta+b");
await page.waitForTimeout(150);
const bcard = () => page.evaluate(() => { const c = document.querySelector(".bookmarks"); return c ? { rows: [...c.querySelectorAll("li")].map((li) => li.textContent.replace(/\s+/g, " ").trim().slice(0, 40)), foot: c.querySelector(".bookmarks-add")?.textContent.replace(/\s+/g, " ").trim(), focused: document.activeElement?.className.split(" ")[0] } : null; });
console.log("⌃⌘B on a day:", JSON.stringify(await bcard()));
await page.keyboard.press("a");
await page.waitForTimeout(300);
console.log("A pressed:", JSON.stringify(await bcard()));
await page.keyboard.press("Escape");
await page.goto(PAGE + "#page/Horace");
await page.waitForFunction(() => document.documentElement.dataset.entry === "page/Horace", null, { timeout: 5000 });
await page.keyboard.press("Control+Meta+b");
await page.waitForTimeout(150);
await page.keyboard.press("1");
await page.waitForFunction(() => document.documentElement.dataset.entry === "2026-09-06", null, { timeout: 5000 });
console.log("1 from Horace:", JSON.stringify({ entry: await page.evaluate(() => document.documentElement.dataset.entry), card: await bcard() }));
await page.keyboard.press("Control+Meta+b");
await page.waitForTimeout(150);
await page.click(".bookmarks .bookmark-setalias");
await page.waitForTimeout(150);
await page.keyboard.type("fb");
await page.keyboard.press("Enter");
await page.waitForTimeout(150);
console.log("keyed fb:", JSON.stringify(await bcard()));
await page.keyboard.press("f");
await page.waitForTimeout(100);
console.log("f typed:", JSON.stringify({ lit: await page.evaluate(() => [...document.querySelectorAll(".bookmarks li.bookmark-typing")].length) }));
await page.keyboard.press("b");
await page.waitForTimeout(150);
console.log("b typed, already here:", JSON.stringify({ card: await bcard(), corner: await page.evaluate(() => document.querySelector(".saved.show")?.textContent) }));
await page.keyboard.press("Control+Meta+b");
await page.waitForTimeout(150);
await page.click(".bookmarks .bookmark-del");
await page.waitForTimeout(150);
console.log("× pressed:", JSON.stringify(await bcard()));
await page.keyboard.press("Escape");
/* the backups panel: the button opens the card; unconfigured, the setup button alone; Escape closes */
await page.click(".toolbtn[title='Automatic folder backups']");
await page.waitForTimeout(100);
console.log("backups:", JSON.stringify(await page.evaluate(() => { const c = document.querySelector(".backups"); return c ? { buttons: [...c.querySelectorAll("button")].map((b) => b.textContent), status: c.querySelector(".backups-status")?.textContent || null } : null; })));
await page.keyboard.press("Escape");
console.log("Escape:", JSON.stringify({ card: await page.evaluate(() => !!document.querySelector(".backups")) }));
/* help: ⌃⌘H opens the card over the entry and closes the pages panel; Escape closes it */
await page.click(".opener[title='Open the pages list']");
await page.keyboard.press("Control+Meta+h");
await page.waitForTimeout(100);
console.log("⌃⌘H over an open pages panel:", JSON.stringify(await page.evaluate(() => ({ help: !document.querySelector(".helppanel").hidden, pages: !!document.querySelector(".pages"), heading: document.querySelector(".helppanel h3")?.textContent }))));
await page.keyboard.press("Escape");
console.log("Escape:", JSON.stringify(await page.evaluate(() => ({ help: !document.querySelector(".helppanel").hidden }))));
/* ⌃⌘G: the bar over verse takes a line, cycles nothing on one block, marks and centres; Escape hands the caret to the row; over a book of leaves the Page box */
await page.goto(PAGE + "#page/Horace");
await page.waitForFunction(() => document.documentElement.dataset.entry === "page/Horace", null, { timeout: 15000 });
await page.keyboard.press("Control+Meta+g");
await page.waitForTimeout(100);
const lbar = () => page.evaluate(() => { const b = document.querySelector(".linebar"); const marked = document.querySelector("#editor .landed"); const r = marked?.getBoundingClientRect(); return { open: !b.hidden, focused: document.activeElement?.id, lineBox: !b.querySelector("label[for=lineinput]").parentElement.hidden, pageBox: !b.querySelector("label[for=folioinput]").parentElement.hidden, marked: marked ? (marked.dataset.line || marked.dataset.folio || marked.className) : null, centred: r ? Math.round((r.top + r.bottom) / 2 - innerHeight / 2) : null, corner: document.querySelector(".saved.show")?.textContent || "" }; });
console.log("⌃⌘G over Horace:", JSON.stringify(await lbar()));
await page.keyboard.type("3");
await page.keyboard.press("Enter");
await page.waitForTimeout(150);
console.log("3, Enter:", JSON.stringify(await lbar()));
await page.keyboard.press("Enter");
await page.waitForTimeout(150);
console.log("Enter again on one block:", JSON.stringify(await lbar()));
await page.keyboard.press("Escape");
await page.waitForTimeout(100);
console.log("Escape:", JSON.stringify({ ...(await lbar()), caretRow: await page.evaluate(() => document.getSelection()?.anchorNode?.parentElement?.closest(".vrow")?.dataset.line) }));
await page.goto(PAGE + "#page/Williams/Witchcraft%203");
await page.waitForFunction(() => document.documentElement.dataset.entry === "page/Williams/Witchcraft 3", null, { timeout: 15000 });
await page.keyboard.press("Control+Meta+g");
await page.waitForTimeout(100);
console.log("⌃⌘G over Witchcraft:", JSON.stringify(await lbar()));
await page.keyboard.type("9z");
await page.keyboard.press("Enter");
await page.waitForTimeout(100);
console.log("9z, Enter:", JSON.stringify(await lbar()));
await page.keyboard.press("Meta+a");
await page.keyboard.type("61");
await page.keyboard.press("Enter");
await page.waitForTimeout(150);
console.log("61, Enter:", JSON.stringify(await lbar()));
await page.keyboard.press("Escape");
/* the dialogs, answered by the harness: `answer` is what a prompt gets, a confirm is accepted */
let answer = null;
page.on("dialog", (d) => { if (d.type() === "confirm") d.accept(); else if (answer !== null) d.accept(answer); else d.dismiss(); });
/* a reference pasted as plain text into the rendered view renders as its markdown */
await page.goto(PAGE + "#page/Pasted");
await page.waitForFunction(() => document.documentElement.dataset.entry === "page/Pasted", null, { timeout: 15000 });
await page.click("#editor .ProseMirror");
await page.evaluate(() => { const dt = new DataTransfer(); dt.setData("text/plain", "[*Gesta*, 7 September 2026](#2026-09-07?h=blind%20cord):\n\n> blind cord"); document.querySelector("#editor .ProseMirror").dispatchEvent(new ClipboardEvent("paste", { clipboardData: dt, bubbles: true, cancelable: true })); });
await page.waitForTimeout(200);
console.log("a reference pasted:", JSON.stringify({ md: await page.evaluate(() => document.getElementById("out")?.textContent), link: await page.evaluate(() => document.querySelector("#editor a")?.getAttribute("href")), quote: await page.evaluate(() => document.querySelector("#editor blockquote")?.textContent) }));
await page.evaluate(() => { const dt = new DataTransfer(); dt.setData("text/plain", "[*Gesta*](#2026-09-06?h=food%20of%20love)"); document.querySelector("#editor .ProseMirror").dispatchEvent(new ClipboardEvent("paste", { clipboardData: dt, bubbles: true, cancelable: true })); });
await page.waitForTimeout(200);
await page.click("#editor a[href='#2026-09-06?h=food%20of%20love']");
await page.waitForFunction(() => document.documentElement.dataset.entry === "2026-09-06" && document.getSelection()?.toString() === "food of love", null, { timeout: 5000 });
await page.waitForTimeout(300);
console.log("the reference link followed:", JSON.stringify(await page.evaluate(() => ({ selected: document.getSelection().toString(), bar: document.querySelector(".fmt").classList.contains("show") }))));
/* the toolbar: a double-click selects a word and floats the bar; B bolds it; Tag moves it out */
await page.goto(PAGE + "#2026-09-06");
await page.waitForFunction(() => document.documentElement.dataset.entry === "2026-09-06", null, { timeout: 15000 });
await page.evaluate(() => scrollTo(0, 0));
const word = await page.evaluate(() => { const w = document.createTreeWalker(document.querySelector("#editor .ProseMirror"), NodeFilter.SHOW_TEXT); let tn; while ((tn = w.nextNode())) if (tn.textContent.includes("music be")) break; const r = document.createRange(); r.setStart(tn, tn.textContent.indexOf("music")); r.setEnd(tn, tn.textContent.indexOf("music") + 5); const b = r.getBoundingClientRect(); tn.parentElement.scrollIntoView({ block: "center" }); const b2 = r.getBoundingClientRect(); return { x: b2.left + b2.width / 2, y: b2.top + b2.height / 2 }; });
await page.mouse.dblclick(word.x, word.y);
await page.waitForFunction(() => document.querySelector(".fmt")?.classList.contains("show"), null, { timeout: 5000 });
await page.waitForTimeout(100);   /* the editor's own selection lands a beat after the DOM's */
const barState = () => page.evaluate(() => { const f = document.querySelector(".fmt"); const r = f.getBoundingClientRect(); return { show: f.classList.contains("show"), selected: document.getSelection().toString(), lit: [...f.querySelectorAll("button.on")].map((b) => b.title.split(" ")[0]), aboveSelection: document.getSelection().rangeCount ? r.bottom < document.getSelection().getRangeAt(0).getBoundingClientRect().top : null, focused: document.activeElement?.className.slice(0, 20), tag: !f.querySelector(".t").hidden }; });
console.log("a word double-clicked:", JSON.stringify(await barState()));
await page.click(".fmt .b");
await page.waitForTimeout(100);
console.log("B clicked:", JSON.stringify({ ...(await barState()), md: await page.evaluate(() => document.getElementById("out").textContent.includes("**music**")) }));
answer = "Music";
await page.click(".fmt .t");
await page.waitForFunction(() => document.documentElement.dataset.entry === "2026-09-06/Music", null, { timeout: 5000 });
console.log("Tag with Music answered:", JSON.stringify({ entry: await page.evaluate(() => document.documentElement.dataset.entry), body: await page.evaluate(() => document.getElementById("out").textContent) }));
await page.goto(PAGE + "#2026-09-06");
await page.waitForFunction(() => document.documentElement.dataset.entry === "2026-09-06", null, { timeout: 5000 });
console.log("the day's text around the link:", JSON.stringify(await page.evaluate(() => { const a = document.querySelector("#editor a[href='#2026-09-06/Music']"); return a && a.parentElement.textContent.slice(0, 40); })));
answer = null;
/* the source view: ⌃⌘M over the day, the caret carried across by its count, an edit in the source landing */
await page.goto(PAGE + "#2026-09-06");
await page.waitForFunction(() => document.documentElement.dataset.entry === "2026-09-06", null, { timeout: 15000 });
await page.evaluate(() => { const w = document.createTreeWalker(document.querySelector("#editor .ProseMirror"), NodeFilter.SHOW_TEXT); let tn; while ((tn = w.nextNode())) if (tn.textContent.includes("food of love")) break; const r = document.createRange(); r.setStart(tn, tn.textContent.indexOf("food of love")); r.collapse(true); const s = document.getSelection(); s.removeAllRanges(); s.addRange(r); });
await page.keyboard.press("Control+Meta+m");
await page.waitForSelector("textarea.source", { timeout: 5000 });
console.log("⌃⌘M:", JSON.stringify(await page.evaluate(() => { const ta = document.querySelector("textarea.source"); return { pill: !document.querySelector(".mode")?.hidden, focused: document.activeElement === ta, sameAsStore: ta.value === document.getElementById("out")?.textContent, caretAt: ta.value.slice(ta.selectionStart, ta.selectionStart + 12) }; })));
await page.keyboard.type("FOOD ");
await page.keyboard.press("Tab");
await page.waitForFunction(() => document.querySelector(".saved.show")?.textContent === "saved", null, { timeout: 5000 }).catch(() => {});
await page.keyboard.press("Control+Meta+m");
await page.waitForSelector("#editor .ProseMirror", { timeout: 5000 });
console.log("⌃⌘M back:", JSON.stringify(await page.evaluate(() => { const s = document.getSelection(); return { pill: !document.querySelector(".mode")?.hidden, text: document.querySelector("#editor .ProseMirror").textContent.includes("FOOD   food of love"), caretBefore: s.anchorNode?.textContent.slice(Math.max(0, s.anchorOffset - 6), s.anchorOffset), caretAfter: s.anchorNode?.textContent.slice(s.anchorOffset, s.anchorOffset + 8), saved: document.getElementById("same")?.textContent }; })));
/* the Go to row: ⌃⌘J on a day, a year pick refilling the months, a day pick navigating; on a book, the chain and the sentinel */
await page.goto(PAGE + "#2026-09-06");
await page.waitForFunction(() => document.documentElement.dataset.entry === "2026-09-06", null, { timeout: 15000 });
await page.keyboard.press("Control+Meta+j");
await page.waitForTimeout(100);
const grow = () => page.evaluate(() => ({ open: document.querySelector(".page-goto")?.open, focused: document.activeElement?.getAttribute("aria-label"), selects: [...document.querySelectorAll(".page-goto select")].map((s) => s.getAttribute("aria-label") + "=" + (s.selectedOptions[0]?.disabled ? "—" : s.value) + " [" + [...s.options].map((o) => o.textContent).join("|") + "]") }));
console.log("⌃⌘J on a day:", JSON.stringify(await grow()));
await page.selectOption(".page-goto select[aria-label='Day']", "05");
await page.waitForFunction(() => document.documentElement.dataset.entry === "2026-09-05", null, { timeout: 5000 });
console.log("a day picked:", JSON.stringify({ entry: await page.evaluate(() => document.documentElement.dataset.entry), open: await page.evaluate(() => document.querySelector(".page-goto")?.open) }));
await page.goto(PAGE + "#bookshelf/Browning,%20Robert/Pippa%20Passes");
await page.waitForFunction(() => document.documentElement.dataset.entry === "bookshelf/Browning, Robert/Pippa Passes", null, { timeout: 15000 });
await page.keyboard.press("Control+Meta+j");
await page.waitForTimeout(100);
console.log("⌃⌘J on a book:", JSON.stringify(await grow()));
await page.selectOption(".page-goto select[aria-label='Destination']", "");
await page.waitForTimeout(100);
console.log("Journal picked from the book:", JSON.stringify((await grow()).selects));
await page.keyboard.press("Escape");
console.log("Escape:", JSON.stringify(await grow()));
/* the sub-entries: the dialogs answered by the harness (declared at the top) */
await page.goto(PAGE + "#2026-09-06");
await page.waitForFunction(() => document.documentElement.dataset.entry === "2026-09-06", null, { timeout: 15000 });
console.log("the masthead over the day after the rows closed:", JSON.stringify(await page.evaluate(() => ({ height: document.querySelector(".site-head").getBoundingClientRect().height, gotoOpen: document.querySelector(".page-goto")?.open, searchOpen: document.querySelector(".page-search")?.open }))));
await page.click("#editor .ProseMirror > :first-child");
await page.keyboard.press("End");
const tools = () => page.evaluate(() => [...document.querySelectorAll(".site-tools .toolbtn")].filter((b) => !b.hidden).map((b) => b.textContent));
console.log("a day's tools:", JSON.stringify(await tools()));
answer = "Ideas";
await page.keyboard.press("Control+Meta+n");
await page.waitForFunction(() => document.documentElement.dataset.entry === "2026-09-06/Ideas", null, { timeout: 5000 });
await page.keyboard.press("Control+Meta+n");
await page.waitForTimeout(100);
console.log("⌃⌘N on the tagged entry:", JSON.stringify(await corner()));
console.log("⌃⌘N, Ideas typed:", JSON.stringify({ entry: await page.evaluate(() => document.documentElement.dataset.entry), crumb: await page.evaluate(() => document.querySelector(".datelabel").textContent.replace(/\s+/g, " ").trim()), tools: await tools() }));
await page.goto(PAGE + "#2026-09-06");
await page.waitForFunction(() => document.documentElement.dataset.entry === "2026-09-06", null, { timeout: 5000 });
console.log("the day's body ends with the link, its tag bar lists it:", JSON.stringify({ link: await page.evaluate(() => { const a = [...document.querySelectorAll("#editor a")].pop(); return a && [a.textContent, a.getAttribute("href")]; }), tags: await page.evaluate(() => [...document.querySelectorAll(".tagbar a")].map((a) => a.textContent)) }));
await page.click(".tagbar a[href='#2026-09-06/Ideas']");
await page.waitForFunction(() => document.documentElement.dataset.entry === "2026-09-06/Ideas", null, { timeout: 5000 });
answer = "Plans";
await page.click(".toolbtn[title=\"Rename this entry's tag\"]");
await page.waitForFunction(() => document.documentElement.dataset.entry === "2026-09-06/Plans", null, { timeout: 5000 });
await page.waitForTimeout(300);
console.log("renamed to Plans:", JSON.stringify({ entry: await page.evaluate(() => document.documentElement.dataset.entry), hash: page.url().split("#")[1], hostLink: await page.evaluate(() => null) }));
await page.goto(PAGE + "#2026-09-06");
await page.waitForFunction(() => document.querySelector("#editor a[href='#2026-09-06/Plans']"), null, { timeout: 5000 }).catch(() => {});
console.log("the host's link followed:", JSON.stringify(await page.evaluate(() => { const a = [...document.querySelectorAll("#editor a")].pop(); return a && [a.textContent, a.getAttribute("href")]; })));
await page.click(".tagbar a[href='#2026-09-06/Plans']");
await page.waitForFunction(() => document.documentElement.dataset.entry === "2026-09-06/Plans", null, { timeout: 5000 });
await page.click(".toolbtn[title='Delete this tagged entry']");
await page.waitForFunction(() => document.documentElement.dataset.entry === "2026-09-06" && !document.querySelector("#editor a[href='#2026-09-06/Plans']"), null, { timeout: 5000 }).catch(() => {});
console.log("deleted: back on the day, its link gone, the other tag left:", JSON.stringify({ entry: await page.evaluate(() => document.documentElement.dataset.entry), links: await page.evaluate(() => [...document.querySelectorAll("#editor a")].map((a) => a.getAttribute("href"))), tags: await page.evaluate(() => [...document.querySelectorAll(".tagbar a")].map((a) => a.textContent)) }));
answer = null;
await page.goto(PAGE + "#page/Brand%20New");
await page.waitForFunction(() => document.documentElement.dataset.entry === "page/Brand New", null, { timeout: 15000 });
await page.click("#editor .ProseMirror");
await page.keyboard.type("- one");
await page.keyboard.press("Enter");
await page.keyboard.type("two");
await page.keyboard.press("Tab");
await page.keyboard.press("Enter");
await page.keyboard.type("three");
await page.keyboard.press("Shift+Tab");
await page.keyboard.press("Shift+Tab");
await page.waitForTimeout(200);
await page.keyboard.press("Enter");
await page.keyboard.press("Enter");
await page.keyboard.type("```");
await page.keyboard.press("Enter");
await page.keyboard.type("code line");
await page.keyboard.press("Enter");
await page.keyboard.press("Enter");
await page.keyboard.type("after the block");
await page.waitForTimeout(200);
console.log("a code block typed, Enter twice out of it:", JSON.stringify({ md: await page.evaluate(() => document.getElementById("out")?.textContent) }));
console.log("a list typed: bullet, Enter, Tab, Enter, Shift-Tab twice:", JSON.stringify({ md: await page.evaluate(() => document.getElementById("out")?.textContent), ...(await corner()) }));
console.log("the gap between the two outer items, and a line's height:", JSON.stringify(await page.evaluate(() => { const li = document.querySelectorAll("#editor ul > li"); const a = li[0].getBoundingClientRect(), b = li[li.length - 1].getBoundingClientRect(); const p = document.querySelectorAll("#editor li > p"); return { outerGapPastNestedList: +(b.top - a.bottom).toFixed(1), lineToNextLine: +(p[1].getBoundingClientRect().top - p[0].getBoundingClientRect().bottom).toFixed(1), line: +p[0].getBoundingClientRect().height.toFixed(1) }; })));
await page.goto(PAGE + "#page/Links");
await page.waitForFunction(() => document.documentElement.dataset.entry === "page/Links", null, { timeout: 15000 });
await page.keyboard.press("Control+Meta+k");
await page.waitForTimeout(100);
const srow = () => page.evaluate(() => ({ open: document.querySelector(".page-search")?.open, focused: document.activeElement?.className, scope: document.querySelector(".page-search select")?.selectedOptions[0]?.textContent, options: [...document.querySelectorAll(".page-search option")].map((o) => o.textContent), rows: [...document.querySelectorAll(".search-results li")].map((li) => li.className + ": " + li.textContent.replace(/\s+/g, " ").trim()) }));
console.log("⌃⌘K:", JSON.stringify(await srow()));
await page.selectOption(".page-search select", "0");
await page.keyboard.type("sister");
await page.waitForFunction(() => document.querySelectorAll(".search-results li").length > 0, null, { timeout: 15000 });
console.log("typed sister:", JSON.stringify(await srow()));
await page.keyboard.press("ArrowDown");
console.log("after ↓:", JSON.stringify((await srow()).rows.filter((r) => r.includes("active"))));
await page.keyboard.press("Enter");
await page.waitForFunction(() => document.getSelection()?.toString().toLowerCase() === "sister", null, { timeout: 5000 }).catch(() => {});
console.log("Enter:", JSON.stringify({ entry: await page.evaluate(() => document.documentElement.dataset.entry), selected: await page.evaluate(() => document.getSelection()?.toString()), open: await page.evaluate(() => document.querySelector(".page-search")?.open) }));
await page.goto(PAGE + "?corner=pill#page/Horace");
await page.waitForFunction(() => document.documentElement.dataset.probe?.includes("all;"), null, { timeout: 15000 });
console.log("with ?corner=pill:", JSON.stringify(await page.evaluate(() => { const b = document.querySelector(".backup-paused"); const r = b.getBoundingClientRect(); return { text: b.textContent, hidden: b.hidden, display: getComputedStyle(b).display, right: innerWidth - r.right, bottom: innerHeight - r.bottom }; })));
if (process.argv[3]) await page.screenshot({ path: process.argv[3].replace(/\.png$/, "-pill.png"), clip: { x: 500, y: 500, width: 500, height: 100 } });
await ctx.close();
console.log("console:", logs.length ? logs.join("\n") : "(nothing)");
